### ISSUE TITLE
Extending to iOS devices

### ISSUE THREAD

**Issue by phongnhhn92** [vincentfpgarcia/from-pytorch-to-coreml#3]
Hi, I am just wondering if your coreML model can be used on iOS devices.
If it is then will it use CPU or GPU to process. I assume the model will run faster on GPU or A14/A13 neural engine.

**Comment by vincent-powder** [comment]
The CoreML model can be used on iOS, macOS, etc.
The inference is done on the neural engine unless specified otherwise (MLPredictionOptions).

**Comment by vincentfpgarcia** [comment]
The CoreML model can be used on iOS, macOS, etc.
The inference is done on the neural engine unless specified otherwise (MLPredictionOptions).
